spring:
  application:
    name: user-service
  config:
    # use optional so that the startup won't fail just because the server is unreachable.
    # don't use optional if config server is the only option.
    import: optional:configserver:http://localhost:8888