services:
  postgres:
    container_name: postgres_container
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # where the database should be stored.
      # default: /var/lib/postgresql/data
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - backend
    restart: unless-stopped

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.4.7
    ports:
      - "8080:8080"
    environment:
      # must create admin since it is not created automatically since keycloak 17
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "true"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HOSTNAME: "keycloak"
      KC_HOSTNAME_PORT: "8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    command: [ "start-dev" ]
    networks:
      - backend

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - backend

  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:4-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # RabbitMQ Message Broker
      - "15672:15672" # RabbitMQ Management UI (http://localhost:15672)
    networks:
      - backend
    restart: unless-stopped


  zipkin: # TODO: running but get errors in gateway
    image: openzipkin/zipkin
    container_name: zipkin_container
    ports:
      - 9411:9411
    networks:
      - backend

  config-server:
    build: ./config-server
    container_name: config-server
    depends_on:
      - rabbitmq
    ports:
      - 8888:8888
    networks:
      - backend
    environment:
#      - SPRING_PROFILES_ACTIVE=docker  # Doesn't work somehow.
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=/config
    volumes:
      - ./config-server/src/main/resources/config:/config

  eureka:
    build: ./eureka
    container_name: eureka
    ports:
      - 7777:7777
    networks:
      - backend
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
    healthcheck:
      test: ["CMD", "wget", "--spider", "https://localhost:7777:/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5 # mark the container unhealthy after 5 consecutive failures.

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend

  gateway-service:
    build: ./gateway
    container_name: gateway
    ports:
      - 8000:8000
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SPRING_RABBITMQ_HOST=rabbitmq
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:7777/eureka
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/gift-shop-app
    depends_on:
      - rabbitmq
      - eureka
      - keycloak
      - config-server
      - redis
      - zipkin
      - product-service
      - user-service
      - order-service
      - notification-service
    networks:
      - backend

  product-service:
    build: ./product
    container_name: product
    ports:
      - 8082:8082
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - config-server
      - eureka
      - zipkin
      - rabbitmq
      - redis
    networks:
      - backend

  user-service:
    build: ./user
    container_name: user
    ports:
      - 8081:8081
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_KEYCLOAK_ADMIN_CLIENT_UID=6fb64d02-a2c7-4feb-bda9-d6bfe2b00cf8
    depends_on:
      - config-server
      - eureka
      - zipkin
      - rabbitmq
      - redis
    networks:
      - backend

  order-service:
    build: ./order
    container_name: order
    ports:
      - 8083:8083
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - config-server
      - eureka
      - zipkin
      - rabbitmq
      - redis
    networks:
      - backend

  notification-service:
    build: ./notification
    container_name: notification
    ports:
      - 8084:8084
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - config-server
      - eureka
      - zipkin
      - rabbitmq
      - redis
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  redis-data:
  keycloak_data: