spring:
  application:
    name: product-service
  config:
    # http://localhost:8888/product-service/default
    # optional is important for being replaced by other files like docker compose.
    import: optional:configserver:http://localhost:8888

