spring:
  datasource: # TODO: talk to another database
    url: jdbc:postgresql://localhost:5432/gift-shop-order-service
    username: postgres # TODO: change to .env !
    password: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details:always

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka
    register-with-eureka: true
    fetch-registry: true

# Circuit Breaker
resilience4j:
  circuitbreaker:
    configs:
      default:
        # Registers this circuit breaker in Spring Boot Actuator health.
        # only visible under actuator/circuitbreakers.
        registerHealthIndicator: true
    instances:
      orderServiceBreaker:
        registerHealthIndicator: true
        slidingWindowType: count_based # time_based
        # Look at last 12 calls and calc the failure rate with them.
        slidingWindowSize: 12
        # Minimum calls required before evaluation starts
        minimumNumberOfCalls: 6
        # How many test calls are allowed when HALF-OPEN.
        permittedNumberOfCallsInHalfOpenState: 3
        # How long the circuit stays OPEN before trying recovery.
        waitDurationInOpenState: 10s
        # Failure percentage needed to OPEN the circuit
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      orderServiceRetry:
        maxAttempts: 5
        waitDuration: 5s
