spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gift-shop-monolith
    username: postgres # TODO: change to .env !
    password: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

# this is for triggering refresh event after the config file is changed at runtime!
management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  message: "Hello Product!"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7
