spring:
  datasource: # TODO: talk to another database
    url: jdbc:postgresql://localhost:5432/gift-shop-monolith
    username: postgres # TODO: change to .env !
    password: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka
    register-with-eureka: true
    fetch-registry: true